/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CalendarComponent: typeof import('./components/CalendarComponent.vue')['default']
    EditorComponent: typeof import('./components/EditorComponent.vue')['default']
    HomeComponent: typeof import('./components/HomeComponent.vue')['default']
    MealsComponent: typeof import('./components/MealsComponent.vue')['default']
    NavigationComponent: typeof import('./components/NavigationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
